### PR TITLE
domain logo and disable autonumbering

### PR DESCRIPTION
**Pull request by costateixeira**
https://github.com/IHE/ihe-ig-template/issues/22 
https://github.com/IHE/ihe-ig-template/issues/23

(Those issues should be moved to this repo and closed when this is merged)

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
I moved the issues

**Review by JohnMoehrke — COMMENTED** [review]
is this needed in the nonum.css?

  /*--------- smooth transitions ---------- */

  body{
      opacity: 0;
      transition: opacity 0.7s;
      -webkit-transition: opacity 0.7s; /* Safari */
      -ms-transition: opacity 0.7s; /* ie */
      -o-transition: opacity 0.7s; /* opera */
      -moz-transition: opacity 0.7s; /* firefox */
  }

**Comment by costateixeira** [comment]
> is this needed in the nonum.css?
> 
> /*--------- smooth transitions ---------- */
> 
> body{ opacity: 0; transition: opacity 0.7s; -webkit-transition: opacity 0.7s; /* Safari _/ -ms-transition: opacity 0.7s; /_ ie _/ -o-transition: opacity 0.7s; /_ opera _/ -moz-transition: opacity 0.7s; /_ firefox */ }

This is for smooth transitions - i don't know where it comes from but I don't think it is critical

**Comment by JohnMoehrke** [comment]
Is it in the normal css, or one of the other? It might simply be unnecessary, and thus should be removed. I would tend to say to not include it. We can aways add it back later, ritght?

**Comment by costateixeira** [comment]
yes, it can be added back later. I didn't touch it because I don't know why it's there.

**Comment by costateixeira** [comment]
@JohnMoehrke feel fre to merge the PR whenever you want - after removing the unneeded css, or doing any more changes
(and hopefully linking to the issues)

**Comment by JohnMoehrke** [comment]
close #22 
close #23

**Pull request merged**
